### PR TITLE
Leaderboard: final touches

### PR DESCRIPTION
**Pull request by VicPeralta**
# Leaderboard: final touches

In this milestone:

- Made sure there are no linter errors.
- Made sure the correct Gitflow was used.
- Work documented in a professional way.
- Improve the look and feel of the application
- Keep the general layout of the wireframe.
- Use plain CSS
- Add a button to reset scores

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
## Hi  @VicPeralta , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


# To Highlights
:arrow_forward: Followed correct Git/GitHub flow :heavy_check_mark: 
:arrow_forward: Correctly set up linters :heavy_check_mark: 
:arrow_forward: App properly styled, very responsive :sweat_smile:  with a good look and feel :heavy_check_mark: 

## Required Changes ♻️

- [ ] Be professional, your API should be easy to understand by people who might want to use it. Your README file should contain all that is needed to run the app with the API it consumes. You may also add instructions about where and how to generate any necessary keys, credentials, how to set, store, and generate them(if necessary).


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by VicPeralta** [comment]
> ## Hi @VicPeralta ,
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! 
> 
> # To Highlights
> ▶️ Followed correct Git/GitHub flow ✔️ ▶️ Correctly set up linters ✔️ ▶️ App properly styled, very responsive 😅 with a good look and feel ✔️
> 
> ## Required Changes ♻️
> * [ ]  Be professional, your API should be easy to understand by people who might want to use it. Your README file should contain all that is needed to run the app with the API it consumes. You may also add instructions about where and how to generate any necessary keys, credentials, how to set, store, and generate them(if necessary).
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello @FrederickMih , thanks for your feedback. I am sorry to tell you that I do not understand the required changes. Do you want me to add a link for the leaderboard API? I didn't write any API, no keys or credentials are needed to run the project.
Could you please elaborate a little more?
Thanks,

**Comment by VicPeralta** [comment]
Readme file updated based on Reviewer's comments

**Review by julie-ify — APPROVED** [review]
Hi @VicPeralta, 

# Status: Approved ✔️ 

Your project is complete!  Your README contains the necessary instructions and info to get the app running 👍. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
